X-HIJA-SYSTEM/Areas/Admin/Controllers/CompanyController.cs
using Ekart.DataAccess.Data;
using Ekart.DataAccess.Repository;
using Ekart.DataAccess.Repository.IRepository;
using Ekart.Models;
using Ekart.Models.ViewModels;
using Ekart.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EkartWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CompanyController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;

        }
        public IActionResult Index()
        {
            List<Company> prodList = _unitOfWork.company.GetAll().ToList();
            return View(prodList);
        }

        public IActionResult Upsert(int? id)
        {

            if (id == 0 || id == null)
            {
                //create
                return View(new Company());
            }
            else
            {
                //update
                Company companyObj = _unitOfWork.company.GetFirstOrDefault(u => u.Id == id);
                return View(companyObj);
            }

        }
        [HttpPost]
        public IActionResult Upsert(Company companyObj)
        {
            if (ModelState.IsValid)
            {
                if (companyObj.Id == 0)
                {
                    _unitOfWork.company.Add(companyObj);
                }
                else
                {
                    _unitOfWork.company.Update(companyObj);
                }
                _unitOfWork.Save();
                TempData["success"] = "Company Created Succssfully";
                return RedirectToAction("Index");
            }
            else
            {
                return View(companyObj);
            }
        }



        #region API CALLS
        [HttpGet]
        public IActionResult ApiGetAll()
        {
            List<Company> companies = _unitOfWork.company.GetAll().ToList();
            return Json(new { data = companies });
        }

        public IActionResult ApiDelete(int? id)
        {
            var CompanyToBeDeleted = _unitOfWork.company.GetFirstOrDefault(u => u.Id == id);
            if (CompanyToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            _unitOfWork.company.Remove(CompanyToBeDeleted);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Deleted successfully" });
        }
        #endregion
    }

}

X-HIJA-SYSTEM/Areas/Admin/Controllers/ProductController.cs
using Ekart.DataAccess.Data;
using Ekart.DataAccess.Repository;
using Ekart.DataAccess.Repository.IRepository;
using Ekart.Models;
using Ekart.Models.ViewModels;
using Ekart.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace EkartWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private object success;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            List<Product> prodList = _unitOfWork.product.GetAll(includeProp: "Category").ToList();
            return View(prodList);
        }

        public IActionResult Upsert(int? id)
        {
            IEnumerable<SelectListItem> CategorySelectList = _unitOfWork.category.GetAll()
                .Select(u => new SelectListItem
                {
                    Text = u.CatName,
                    Value = u.CatID.ToString()
                });

            ProductVM productVM = new ProductVM()
            {
                CategoryList = CategorySelectList,
                product = new Product()
            };
            if (id == 0 || id == null)
            {
                return View(productVM);
            }
            else
            {
                productVM.product = _unitOfWork.product.GetFirstOrDefault(u => u.Id == id);
                return View(productVM);
            }

        }
        [HttpPost]
        public IActionResult Upsert(ProductVM productVM, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string productPath = Path.Combine(wwwRootPath, @"images\product");

                    if (!string.IsNullOrEmpty(productVM.product.ImageUrl))
                    {
                        //delete the old image
                        var oldImagePath =
                            Path.Combine(wwwRootPath, productVM.product.ImageUrl.TrimStart('\\'));

                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    productVM.product.ImageUrl = @"\images\product\" + fileName;
                }

                if (productVM.product.Id == 0)
                {
                    _unitOfWork.product.Add(productVM.product);
                }
                else
                {
                    _unitOfWork.product.Update(productVM.product);
                }

                _unitOfWork.Save();
                TempData["success"] = "Product Created Succssfully";
                return RedirectToAction("Index");
            }
            else
            {
                productVM.CategoryList = _unitOfWork.category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.CatName,
                    Value = u.CatID.ToString()
                });
                return View(productVM);
            }
        }

        /*   public IActionResult Delete(int? id)
           {
               if (id == null || id == 0)
               {
                   return NotFound();
               }
               Product? product = _unitOfWork.product.GetFirstOrDefault(u => u.Id == id);
               if (product == null)
               {
                   return NotFound();
               }
               return View(product);
           }

           [HttpPost, ActionName("Delete")]
           public IActionResult DeletePOST(int? id)
           {
               Product? product = _unitOfWork.product.GetFirstOrDefault(u => u.Id == id);
               if (product == null)
               {
                   return NotFound(null);
               }

               _unitOfWork.product.Remove(product);
               _unitOfWork.Save();
               TempData["success"] = "Category Deleted Succssfully";
               return RedirectToAction("Index");

           }
   */

        #region API CALLS
        [HttpGet]
        public IActionResult ApiGetAll()
        {
            List<Product> prodList = _unitOfWork.product.GetAll(includeProp: "Category").ToList();
            return Json(new { data = prodList });
        }

        public IActionResult ApiDelete(int? id)
        {
            var productToBeDeleted = _unitOfWork.product.GetFirstOrDefault(u => u.Id == id);
            if (productToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            var oldImagePath =
                        Path.Combine(_webHostEnvironment.WebRootPath, productToBeDeleted.ImageUrl.TrimStart('\\'));

            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
            _unitOfWork.product.Remove(productToBeDeleted);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Deleted successfully" });
        }
        #endregion
    }


}

X-HIJA-SYSTEM/Areas/Admin/Views/Company/Delete.cshtml
@model Product

<div class="card shadow border-0 mt-4 mx-auto" style="width:90%">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Delete Product</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="Id" hidden />
            <div class="border p-3 mt-4">

                <div class="form-floating py-2 col-12">
                    <input asp-for="Title" disabled class="form-control border-0 shadow" />
                    <label asp-for="Title" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Description" disabled class="form-control border-0 shadow" />
                    <label asp-for="Description" class="ms-2"></label>
                </div> <div class="form-floating py-2 col-12">
                    <input asp-for="ISBN" disabled class="form-control border-0 shadow" />
                    <label asp-for="ISBN" class="ms-2"></label>
                </div> <div class="form-floating py-2 col-12">
                    <input asp-for="Author" disabled class="form-control border-0 shadow" />
                    <label asp-for="Author" class="ms-2"></label>
                </div> <div class="form-floating py-2 col-12">
                    <input asp-for="ListPrice" disabled class="form-control border-0 shadow" />
                    <label asp-for="ListPrice" class="ms-2"></label>
                </div> <div class="form-floating py-2 col-12">
                    <input asp-for="Price" disabled class="form-control border-0 shadow" />
                    <label asp-for="Price" class="ms-2"></label>
                </div> <div class="form-floating py-2 col-12">
                    <input asp-for="Price50" disabled class="form-control border-0 shadow" />
                    <label asp-for="Price50" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Price100" disabled class="form-control border-0 shadow" />
                    <label asp-for="Price100" class="ms-2"></label>

                </div>

                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger form-control">Delete</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Product" asp-action="Index" class="btn btn-secondary border  form-control">
                            Back to List
                        </a>
                    </div>
                </div>

            </div>
        </form>
    </div>

</div>
<br />
<br />
<br />
<br />
<br />

X-HIJA-SYSTEM/Areas/Admin/Views/Company/Index.cshtml
@model List<Company>

<div class="card shadow border-0 mb-5">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">COMPANY LIST</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4 ">
        <div class="row pb-3">
            <div class="col-6">
                   </div>
            <div class="col-6 text-end">
                <a asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i>  Create New Company
                </a>
            </div>
        </div>
        <table id="tblCompany" class="table table-bordered table-striped border-1" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Address</th>
                    <th>City</th>
                    <th>State</th>
                    <th>Postal Code</th>
                    <th>Phone Number</th>
                    <th></th>
                </tr>
            </thead>

        </table>

    </div>
</div>
<br />
<br />
<br />

@section Scripts{
    <script src="~/js/company.js"></script>
}

X-HIJA-SYSTEM/Areas/Admin/Views/Company/Upsert.cshtml
@model Company

<div class="card shadow border-0 mt-4 mx-auto" style="width:90%">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">@(Model.Id != 0 ? "UPDATE" : "CREATE") COMPANY</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input hidden asp-for="Id" />
            <div class="row">
                <div class="col-12">
                    <div class="border p-3">
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Name" class="form-control border-0 shadow" />
                            <label asp-for="Name" class="ms-2"></label>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                     <div class="form-floating py-2 col-12">
                            <input asp-for="Address" class="form-control border-0 shadow" />
                            <label asp-for="Address" class="ms-2"></label>
                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="City" class="form-control border-0 shadow" />
                            <label asp-for="City" class="ms-2"></label>
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="State" class="form-control border-0 shadow" />
                            <label asp-for="State" class="ms-2"></label>
                            <span asp-validation-for="State" class="text-danger"></span>
                        </div>

                        <div class="form-floating py-2 col-12">
                            <input asp-for="PhoneNumber" class="form-control border-0 shadow" />
                            <label asp-for="PhoneNumber" class="ms-2"></label>
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="PostalCode" class="form-control border-0 shadow" />
                            <label asp-for="PostalCode" class="ms-2"></label>
                            <span asp-validation-for="PostalCode" class="text-danger"></span>
                        </div>

                        <div class="row pt-2">
                            <div class="col-6 col-md-3">
                                @if (Model.Id == 0)
                                {
                                    <button type="submit" class="btn btn-primary form-control">CREATE</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary form-control">UPDATE</button>
                                }
                            </div>
                            <div class="col-6 col-md-3">
                                <a asp-controller="Company" asp-action="Index" class="btn btn-secondary border form-control">
                                    Back to List
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </form>
    </div>
</div>
<br />
<br />
<br />
<br />
<br />

@section Scripts {
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'ai tinycomments anchor autolink charmap codesample emoticons link lists searchreplace  wordcount checklist  autocorrect',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | align lineheight | removeformat',
            tinycomments_mode: 'embedded',
            tinycomments_author: 'Author name',
            mergetags_list: [
                { value: 'First.Name', title: 'First Name' },
                { value: 'Email', title: 'Email' },
            ],
            ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant")),
        });
    </script>

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}